step: all

steps:
  - data_load

data_load:
  raw_data_path: "../../data/raw/"
  output_path: "../../data/processed/"

model:
  batch_size: 32
  epochs: 5
  learning_rate: 0.001
  input_shape: [1, 28, 28]  # PyTorch uses [C, H, W]
  num_classes: 10
  save_path: models/pytorch_mnist_model.pth