name: MNIST_NUM_DETECT
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.10.3
  - seaborn=0.13.2
  - scikit-learn=1.6.1
  - scipy=1.11.4
  - pytorch=2.2.2
  - torchvision=0.15.2
  - torchaudio=2.2.2
  - pyyaml=6.0.2
  - pip=25.1.1
  - pytest=8.3.5

  - pip:
    - tensorflow==2.13.0
    - keras==2.13.1
    - mlflow
    - click
    - hydra-core==1.3.2
    - omegaconf==2.3.0
    - opencv-python==4.11.0.86
    - -e .