name: MNIST_NUM_DETECT
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - pytorch
  - torchvision
  - torchaudio
  - pyyaml
  - pip
  - pytest

  - pip:
    - tensorflow
    - keras
    - mlflow
    - click
    - hydra-core
    - omegaconf
    - opencv-python
    - fastapi
    - python-multipart
    - uvicorn
    - -e .