name: MNIST_NUM_DETECT

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pyyaml
  - typer
  - loguru
  - tqdm
  - black
  - flake8
  - isort
  - pytest
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - seaborn
  
  - pip:
      - tensorflow==2.15.0
      - opencv-python
      - ultralytics
      - ultralytics-thop
      - python-dotenv
      - mkdocs
