name: object_detect_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - torch=1.12.0
  - torchvision=0.13.0
  - torchaudio
  - tqdm
  - pip:
      - opencv-python
      - ultralytics
      - ultralytics-thop