name: MNIST_NUM_DETECT

channels:
  - conda-forge
  - defaults
  - pytorch  # Explicitly add this for more robust PyTorch resolution

dependencies:
  - python=3.10
  - pip
  - typer
  - loguru
  - tqdm
  - black
  - flake8
  - isort
  - pytest
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pytorch=2.1  # or 2.0 if 2.1 fails
  - torchvision=0.16
  - torchaudio=2.1

  - pip:
      - opencv-python
      - ultralytics
      - ultralytics-thop
      - python-dotenv
      - mkdocs
