name: MNIST_NUM_DETECT
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10.12
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.10.3
  - seaborn=0.13.2
  - scikit-learn=1.6.1
  - scipy=1.11.4
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - pyyaml=6.0.2
  - pip=25.1.1
  - pytest=8.3.5

  - pip:
      - tensorflow==2.15.0
      - opencv-python==4.11.0.86
      - mlflow==2.9.2
      - click==8.1.7
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - fastapi==0.104.1
      - python-multipart==0.0.9
      - uvicorn==0.27.1
      - wandb==0.20.1
      - python-dotenv==1.0.0
      - -e .

      
