name: MNIST_NUM_DETECT
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - pyyaml
  - pytest
  - fastapi
  - python-multipart
  - uvicorn
  - opencv
  - pip
  - pip:
      - -e .
