name: object_detect_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - torch
  - torchvision
  - torchaudio
  - tqdm
  - pip:
      - opencv-python
      - ultralytics
      - ultralytics-thop