step: all

steps:
  - data_load
  - data_validation
  - data_preprocess
  - model
  - evaluation
  - features
  - inference

paths:
  raw_data: data/raw
  processed_data: data/processed
  model: models/model.pth                # used by main.py
  reports: reports/embeddings
  figures: reports/figures
  predictions: predictions/prediction.txt

model:
  batch_size: 32
  epochs: 5
  learning_rate: 0.001
  input_shape: [1, 28, 28]
  num_classes: 10