name: YOLOv5 CI with Conda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda with Mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          use-mamba: true                # 🔥 Faster dependency solver
          environment-file: environment.yml
          activate-environment: object_detect_env
          python-version: 3.9

      - name: Verify torch is installed
        run: python -c "import torch; print(torch.__version__)"