name: Coverage Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mlops-env
          environment-file: environment.yaml
          auto-activate-base: false

      - name: Install test dependencies
        shell: bash -l {0}
        run: |
          conda install -y pytest pytest-cov

      - name: Run tests with coverage
        shell: bash -l {0}
        run: |
          pytest --cov=. --cov-fail-under=50 